---

- debug:
    msg: "Applying hostgroup desktop"
  tags:
  - always
  - desktop

#- debug:
#    msg: "{{ (roles_base + roles_server + roles_headless + roles_desktop + roles_group + roles_host) | list }}"
#  tags: always

- name: include a role from a list of 'roles'
  ansible.builtin.include_role:
    name: "{{ hg_desktop_r }}"
    allow_duplicates: no
    apply:
      tags:
      - desktop
  loop: "{{ (roles_base + roles_server + roles_headless + roles_desktop + roles_group + roles_host) | list }}"
  loop_control:
    loop_var: hg_desktop_r
  tags:
  - always
