---

- debug:
    msg: "Applying hostgroup desktop"
  tags:
  - always

#- debug:
#    msg: "{{ (roles_base + roles_server + roles_headless + roles_desktop + roles_group + roles_host) | list }}"
#  tags: always

- name: include a role from a list of 'roles'
  ansible.builtin.include_role:
    name: "{{ r }}"
    allow_duplicates: no
  loop: "{{ (roles_base + roles_server + roles_headless + roles_desktop + roles_group + roles_host) | list }}"
  loop_control:
    loop_var: r
  tags:
  - always

