---

- debug:
    msg: "Applying hostgroup headless"
  tags:    
  - always
  - headless

- name: include a role from a list of 'roles'
  ansible.builtin.include_role:
    name: "{{ hg_headless_r }}"
    allow_duplicates: no
    public: yes
    apply:
      tags:
      - headless
  loop: "{{ (roles_base + roles_server + roles_headless + roles_group + roles_host) | list }}"
  loop_control:
    loop_var: hg_headless_r
  tags:
  - always
